![](profile.jpg)

I am currently a [DAAD] Research Fellow at [NII], Tokyo supervised by
[Zhenjiang Hu]. See my [CV] for a summary of what I did previously.

[DAAD]: http://www.daad.de/en/index.html
[NII]: http://www.nii.ac.jp/en/
[Zhenjiang Hu]: http://research.nii.ac.jp/~hu/
[Dr.rer.nat.]: http://en.wikipedia.org/wiki/Doctor_of_Science#Germany.2C_Austria.2C_Switzerland
[University of Kiel]: http://www.uni-kiel.de/
[old website]: http://www-ps.informatik.uni-kiel.de/~sebf/
[CV]: cv.pdf

Contact
-------

+--------------+-----------------------------------------+
| __Address__: | ~~~                                     |
|              | Sebastian Fischer                       |
|              | DAAD Research Fellow                    |
|              | National Institute of Informatics (NII) |
|              | 2-1-2, Hitotsubashi, Chiyoda-ku, Tokyo  |
|              | 101-8430                                |
|              | ~~~                                     |
|              |                                         |
|              | ~~~                                     |
|              | セバスティアン　フィッシャー                  |
|              | DAAD特別研究員                            |
|              | 国立情報学研究所（NII）                     |
|              | 〒101-8430　東京都千代田区一ツ橋2-1-2        |
|              | ~~~                                     |
+--------------+-----------------------------------------+
|  __E-Mail__: | [fischer@nii.ac.jp] ([encryption])      |
+--------------+-----------------------------------------+
|   __Skype__: | federigo.pescatore                      |
+--------------+-----------------------------------------+

[fischer@nii.ac.jp]: mailto:fischer@nii.ac.jp
[encryption]: fischer.gpgkey

Research Interests
------------------

 - functional and functional-logic programming languages
 - programming with (free) algebraic structures
 - languages to describe implicitly parallel computations

Open Source Projects
--------------------

I maintain [Haskell] libraries for

 - efficient regular expression matching ([weighted-regexp]),
 - generation of bar charts from text files ([barchart]),
 - monadic formulation of search problems ([tree-monad],
   [stream-monad], [level-monad], [explicit-sharing]),
 - and efficient computation of [primes] and [fibonacci] numbers.

[Haskell]: http://haskell.org/

[weighted-regexp]: http://sebfisch.github.com/haskell-regexp/
[barchart]: http://sebfisch.github.com/haskell-barchart/

[tree-monad]: http://hackage.haskell.org/package/tree-monad
[stream-monad]: http://hackage.haskell.org/package/stream-monad
[level-monad]: http://hackage.haskell.org/package/level-monad
[explicit-sharing]: http://hackage.haskell.org/package/explicit-sharing
[primes]: http://hackage.haskell.org/package/primes
[fibonacci]: http://hackage.haskell.org/package/fibonacci

See [my github page] for a complete list of my open source projects.

[my github page]: https://github.com/sebfisch

<a name="publications"></a>

Scientific Activities
---------------------

 - Program Commitee member of the [20th International Workshop on
   Functional and (Constraint) Logic Programming, WFLP 2011][WFLP'11]

[WFLP'11]: http://www.wi.uni-muenster.de/pi/konferenzen/wflp2011/wflp2011.htm

Publications
------------
[BibTeX entries](bibtex.html)

$publications:publication()$

